### ISSUE TITLE
Warnings due to use of gs

### ISSUE THREAD

**Issue by VorpalBlade** [tonyg/erlang-serial#11]
When building erlang-serial the following warnings now occur (using OTP/17):
```
src/terminal.erl:95: Warning: gs:start/0: the gs application has been deprecated and will be removed in OTP 18; use the wx application instead
src/terminal.erl:96: Warning: gs:create/3: the gs application has been deprecated and will be removed in OTP 18; use the wx application instead
[... a lot more of these ...]
```
Presumably it will not even compile with OTP/18. I would also like to be able to build this on a headless system without any GUI support installed (not even X11).

**Comment by tonyg** [comment]
Good call. Perhaps the GUI part should be split out or even removed. What would you recommend?

**Comment by tonyg** [comment]
I've moved it to the `examples/` folder, lacking time to modernise the code.

**Comment by VorpalBlade** [comment]
This solution works fine for me, I'm not especially interested in the GUI terminal.
